#!/bin/bash

for key in "$@" ; do
  case $key in
    -e|--exclude-models)
      EXCLUDE_MODELS=true
      shift
      ;;
    -i=*|--identifier=*)
      IDENTIFIER="${key#*=}"
      shift
      ;;
  esac
done

if [ "$IDENTIFIER" != "" ]; then
  IDENTIFIER="${IDENTIFIER}_"
fi

NOW=$(date +"%Y-%m-%d_%H-%M-%S")
cd ..
mkdir -p smart/archive

tar -czvf "smart-$IDENTIFIER$NOW.tar.gz" --exclude=smart/local --exclude=smart/archive --exclude=*model.checkpoint --exclude=*vocab.txt --exclude=*special_tokens_map.json smart
mv "smart-$IDENTIFIER$NOW.tar.gz" smart/archive

if [ "$EXCLUDE_MODELS" = true ]; then
  echo "INFO: Model checkpoints excluded"
else
  echo "INFO: Model checkpoints included"
  tar -czvf "smart-$IDENTIFIER$NOW-all.tar.gz" --exclude=smart/local --exclude=smart/archive smart
  mv "smart-$IDENTIFIER$NOW-all.tar.gz" smart/archive
fi
