#!/bin/bash

export PYTHONPATH="$(pwd):$PYTHONPATH"
export PYTHONHASHSEED=42

echo "INFO: Python hash seed = $PYTHONHASHSEED"

python3 smart/main.py test $1 $2

echo "WARNING: Don't forget to freeze by executing 'bash freeze'"
